name: Blast2Tree
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.13
  - bedtools=2.31.1
  - blast=2.16.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cairo=1.18.2
  - cap3=10.2011
  - curl=8.12.1
  - entrez-direct=22.4
  - figtree=1.4.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - gawk=5.3.1
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - giflib=5.2.2
  - gmp=6.3.0
  - graphite2=1.3.13
  - harfbuzz=10.4.0
  - icu=75.1
  - iqtree=2.4.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libcups=2.3.3
  - libcurl=8.12.1
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libglib=2.82.2
  - libgomp=14.2.0
  - libiconv=1.18
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblzma=5.6.4
  - libmpdec=4.0.0
  - libnghttp2=1.64.0
  - libpng=1.6.47
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - mafft=7.525
  - mpfr=4.2.1
  - ncbi-vdb=3.2.0
  - ncurses=6.5
  - openjdk=23.0.2
  - openssl=3.4.1
  - pcre2=10.44
  - perl=5.32.1
  - perl-archive-tar=2.40
  - perl-carp=1.50
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.202
  - perl-encode=3.21
  - perl-exporter=5.74
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-io-compress=2.201
  - perl-io-zlib=1.14
  - perl-json=4.10
  - perl-json-xs=4.03
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-parent=0.243
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.68
  - perl-storable=3.15
  - perl-types-serialiser=1.01
  - pip=25.0.1
  - pixman=0.44.2
  - pthread-stubs=0.4
  - python=3.13.2
  - python_abi=3.13
  - readline=8.2
  - rpsbproc=0.5.0
  - tk=8.6.13
  - trimal=1.5.0
  - tzdata=2025a
  - wget=1.21.4
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.11
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - zlib=1.3.1
  - zstd=1.5.7
