name: Blast2Tree
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bedtools=2.31.1
  - blast=2.16.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cap3=10.2011
  - curl=8.12.1
  - entrez-direct=22.4
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - iqtree=2.4.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libcurl=8.12.1
  - libedit=3.1.20250104
  - libev=4.33
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgomp=14.2.0
  - libidn2=2.3.7
  - liblzma=5.6.4
  - libnghttp2=1.64.0
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libunistring=0.9.10
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - muscle=5.3
  - ncbi-vdb=3.2.0
  - ncurses=6.5
  - openssl=3.4.1
  - perl=5.32.1
  - perl-archive-tar=2.40
  - perl-carp=1.50
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.202
  - perl-encode=3.21
  - perl-exporter=5.74
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-io-compress=2.201
  - perl-io-zlib=1.14
  - perl-json=4.10
  - perl-json-xs=4.03
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-parent=0.243
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.68
  - perl-storable=3.15
  - perl-types-serialiser=1.01
  - rpsbproc=0.5.0
  - trimal=1.5.0
  - wget=1.21.4
  - zlib=1.3.1
  - zstd=1.5.7
